//search courses
export const SEARCH_COURSE = "SEARCH_COURSE";
// COURSE ACTION
export const FETCH_COURSES_REQUEST = "FETCH_COURSES_REQUEST";
export const FETCH_COURSES_COMPLETE = "FETCH_COURSES_COMPLETE";
export const FETCH_COURSES_FAILED = "FETCH_COURSES_FAILED";

//Curse Detail
export const GET_COURSE_DETAIL_REQUEST = "GET_COURSE_DETAIL_REQUEST";
export const GET_COURSE_DETAIL_SUCCESS = "GET_COURSE_DETAIL_SUCCESS";
export const GET_COURSE_DETAIL_FAILED = "GET_COURSE_DETAIL_FAILED";

// Enroll Course
export const POST_ENROLL_COURSE = "POST_ENROLL_COURSE";
export const GET_STUDENT_COURSE = "GET_STUDENT_COURSE";


// USER
export const GET_USER_PROFILE_PENDING = "GET_USER_PROFILE_PENDING";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILED = "GET_USER_PROFILE_FAILED";
export const USER_SIGNUP = "USER_SIGNUP";
export const USER_SIGNIN = "USER_SIGNIN";