//search courses
export const SEARCH_COURSE_REQUEST = "SEARCH_COURSE_REQUEST";
export const SEARCH_COURSE_SUCCESS = "SEARCH_COURSE";
export const SEARCH_COURSE_FAILED = "SEARCH_COURSE_FAILED";
// COURSE ACTION
export const FETCH_COURSES_REQUEST = "FETCH_COURSES_REQUEST";
export const FETCH_COURSES_COMPLETE = "FETCH_COURSES_COMPLETE";
export const FETCH_COURSES_FAILED = "FETCH_COURSES_FAILED";

//Curse Detail
export const GET_COURSE_DETAIL_REQUEST= "GET_COURSE_DETAIL_REQUEST";
export const GET_COURSE_DETAIL_SUCCESS= "GET_COURSE_DETAIL_SUCCESS";
export const GET_COURSE_DETAIL_FAILED= "GET_COURSE_DETAIL_FAILED";
export const RELATED_COURSE_REQUEST= "RELATED_COURSE_REQUEST";
export const RELATED_COURSE_SUCCESS= "RELATED_COURSE_SUCCESS";
export const RELATED_COURSE_FAILED= "RELATED_COURSE_FAILED";

