//search courses
export const SEARCH_COURSE_REQUEST = "SEARCH_COURSE_REQUEST";
export const SEARCH_COURSE_SUCCESS = "SEARCH_COURSE";
export const SEARCH_COURSE_FAILED = "SEARCH_COURSE_FAILED";
// COURSE ACTION
export const FETCH_COURSES_REQUEST = "FETCH_COURSES_REQUEST";
export const FETCH_COURSES_COMPLETE = "FETCH_COURSES_COMPLETE";
export const FETCH_COURSES_FAILED = "FETCH_COURSES_FAILED";

//Curse Detail
export const GET_COURSE_DETAIL_REQUEST= "GET_COURSE_DETAIL_REQUEST";
export const GET_COURSE_DETAIL_SUCCESS= "GET_COURSE_DETAIL_SUCCESS";
export const GET_COURSE_DETAIL_FAILED= "GET_COURSE_DETAIL_FAILED";
export const RELATED_COURSE_REQUEST= "RELATED_COURSE_REQUEST";
export const RELATED_COURSE_SUCCESS= "RELATED_COURSE_SUCCESS";
export const RELATED_COURSE_FAILED= "RELATED_COURSE_FAILED";

// Enroll Course
export const POST_ENROLL_COURSE = "POST_ENROLL_COURSE";
export const GET_STUDENT_COURSE = "GET_STUDENT_COURSE";

// USER
export const GET_USER_PROFILE_PENDING = "GET_USER_PROFILE_PENDING";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILED = "GET_USER_PROFILE_FAILED";

export const UPLOAD_PROFILE_IMAGE = "UPLOAD_PROFILE_IMAGE";
export const UPDATE_USER = "UPDATE_USER";

// STUDENT
export const GET_POP_UP_MATERIAL_REQUEST = "GET_POP_UP_MATERIAL_REQUEST";
export const GET_POP_UP_MATERIAL_SUCCESS = "GET_POP_UP_MATERIAL_SUCCESS";
export const GET_POP_UP_MATERIAL_FAILED = "GET_POP_UP_MATERIAL_FAILED";
export const GET_POP_UP_CONTENT_REQUEST = "GET_POP_UP_CONTENT_REQUEST";
export const GET_POP_UP_CONTENT_SUCCESS = "GET_POP_UP_CONTENT_SUCCESS";
export const GET_POP_UP_CONTENT_FAILED = "GET_POP_UP_CONTENT_FAILED";
export const USER_SIGNUP = "USER_SIGNUP";
export const USER_SIGNIN = "USER_SIGNIN";
export const USER_LOGOUT = "USER_LOGOUT";
